name: 'IntelliCode Team Model Training'
description: 'Github Action used to access IntelliCode services on CI builds.'
author: 'Microsoft'
inputs:
  platform:
    description: 'Only for C++ extractions. Sets the platform for the C++ build (ARM, Any CPU, etc).'
    required: false
  config:
    description: 'Only for C++ extractions. Sets the configuration for the C++ build (Debug, Release).'
    required: false
  directory:
    description: 'Use if you wish to override the directory where the repo to be trained is located at.'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
